version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh node index.js
    networks:
      - node-network
    tty: true
    volumes:
      - ./node:/app
      - /app/node_modules
    depends_on:
      - db
  
  nginx:
    restart: always
    build:
      context: nginx
    ports:
      - "8080:80"
    networks:
      - node-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - node/.env
    networks:
      - node-network

networks:
  node-network:
    driver: bridge